### ISSUE TITLE
load custom JS

### ISSUE THREAD

**Issue by Kikobeats** [docpress/docpress-core#82]
Docs says that is possible load custom CSS:

https://docpress.github.io/customization/css.html

What about load custom JS? Also could be nice select header or footer.

**Comment by knownasilya** [comment]
@rstacruz any comments on this?

I think you can add a `docs/assets/script.js` file that will be included in the template..

**Comment by knownasilya** [comment]
This works

<img width="536" alt="screen shot 2016-08-15 at 3 14 23 pm" src="https://cloud.githubusercontent.com/assets/34726/17676126/02188786-62fb-11e6-8be3-d14cabd3449d.png">

I'll open a PR so we can discuss.

**Comment by rstacruz** [comment]
Sure, custom js should work too!

**Comment by Kikobeats** [comment]
nice! docs also necessary 😄

**Comment by knownasilya** [comment]
https://github.com/docpress/docpress/pull/127
